import puppeteer from 'puppeteer';
import fs from 'fs';
import https from 'https';

function fetch(url) {
  return new Promise((resolve, reject) => {
    https.get(url, (res) => {
      let d = '';
      res.on('data', (c) => (d += c));
      res.on('end', () => resolve(d));
    }).on('error', reject);
  });
}

const TARGETS = ['.st0', '.st1', '.st2', '.st3', '.st4', '#interactive-map', '.info-text', '.legend', '.legend-text'];

const browser = await puppeteer.launch({ headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.goto('https://ecustoms.sgs.com/', { waitUntil: 'networkidle2', timeout: 120000 });
await new Promise((r) => setTimeout(r, 2000));

const audit = await page.evaluate((targets) => {
  const map = document.querySelector('#interactive-map');
  const mapNodes = map ? [map, ...map.querySelectorAll('*')] : [];
  const ancestors = [];
  let n = map?.parentElement;
  while (n && n !== document.documentElement) { ancestors.push(n); n = n.parentElement; }
  const allNodes = [...ancestors, ...mapNodes];

  const byStylesheet = {};

  for (const sheet of Array.from(document.styleSheets)) {
    const href = sheet.href || 'inline';
    const owner = sheet.ownerNode?.getAttribute?.('data-type') || sheet.ownerNode?.id || 'inline';
    const key = href === 'inline' ? `inline:${owner}` : href;

    let rules;
    try { rules = sheet.cssRules; } catch (e) { continue; }

    const walk = (list, media = null) => {
      for (const rule of Array.from(list)) {
        if (rule.type === CSSRule.MEDIA_RULE) { walk(rule.cssRules, rule.conditionText); continue; }
        if (rule.type !== CSSRule.STYLE_RULE) continue;
        const selector = rule.selectorText;
        if (!selector) continue;

        const touches = targets.some((t) => selector.toLowerCase().includes(t.toLowerCase().replace(/^[#.]/, '')) && (
          selector.toLowerCase().includes(t.toLowerCase()) ||
          (t === '.legend' && /\blegend\b/.test(selector) && !selector.includes('vc_chart'))
        ));

        let matches = false;
        for (const node of allNodes) {
          try { if (node.matches(selector)) { matches = true; break; } } catch (e) {}
        }

        if (!touches && !matches) continue;
        if (selector.includes('vc_chart')) continue;

        if (!byStylesheet[key]) byStylesheet[key] = { href: key, owner, rules: [] };
        byStylesheet[key].rules.push({ media, selector, cssText: rule.cssText, matchesDom: matches });
      }
    };
    walk(rules);
  }
  return byStylesheet;
}, TARGETS);

await browser.close();

const scss = await fetch('https://ecustoms.sgs.com/wp-content/custom_codes/1243-scss-output.css?ver=278');
const vcPage = await fetch('https://ecustoms.sgs.com/');
const vc = vcPage.match(/<style data-type="vc_custom-css">([\s\S]*?)<\/style>/)?.[1]?.trim();

let md = `# CSS audit — live WordPress map on ecustoms.sgs.com\n\n`;
md += `Generated by \`node scripts/audit-css.mjs\`\n\n`;
md += `## Stylesheets with rules affecting map selectors\n\n`;

for (const [key, sheet] of Object.entries(audit)) {
  if (!sheet.rules.length) continue;
  md += `### ${key}\n\n`;
  md += `Owner: ${sheet.owner}\n\n`;
  for (const r of sheet.rules) {
    const media = r.media ? `@media ${r.media} ` : '';
    md += `- \`${media}${r.selector}\`${r.matchesDom ? ' *(matches DOM)*' : ''}\n`;
    md += `  \`\`\`css\n  ${r.cssText}\n  \`\`\`\n`;
  }
  md += '\n';
}

md += `## Reproduced in standalone styles.css\n\n`;
md += `1. Theme reset (\`*\`) and \`body\` from dt-the7 computed values\n`;
md += `2. Map block extracted verbatim from \`1243-scss-output.css\` (lines .map-container through circle.st4.export)\n`;
md += `3. \`vc_custom-css\` inline block verbatim from page <head>\n\n`;
md += `Run \`node scripts/generate-styles.mjs\` to regenerate styles.css from live sources.\n`;

fs.writeFileSync('CSS-AUDIT.md', md);
fs.writeFileSync('scripts/output/css-audit.json', JSON.stringify(audit, null, 2));
console.log('Wrote CSS-AUDIT.md');
